import { IUser } from "src/interfaces/IUser";

export const userListData: Array<IUser> = [
  {
    acceptTerms: true,
    accessLevel: 'boss',
    areaOfIntrest: 'café',
    corp: 'The Public house',
    corpEmail: 'mateus@thepublic.house',
    email: 'spntn.mateus@gmail.com',
    id: 1,
    firstAccess: false,
    name: 'Mateus Sponton',
    partOf: true,
    passwordHash: '',
    passwordResetToken: '',
    passwordSalt: '',
    phone: '',
    resetTokenExpires: '',
    role: '',
    rpmId: 1,
    verificationToken: '',
    verifiedAt: ''
  },
    {
    acceptTerms: true,
    accessLevel: 'boss',
    areaOfIntrest: 'café',
    corp: 'The Public house',
    corpEmail: 'marco@thepublic.house',
    email: '',
    id: 2,
    firstAccess: false,
    name: 'Marco Antônio',
    partOf: true,
    passwordHash: '',
    passwordResetToken: '',
    passwordSalt: '',
    phone: '',
    resetTokenExpires: '',
    role: '',
    rpmId: 2,
    verificationToken: '',
    verifiedAt: ''
  },
  {
    acceptTerms: true,
    accessLevel: 'boss',
    areaOfIntrest: 'café',
    corp: 'The Public house',
    corpEmail: 'caio@thepublic.house',
    email: '',
    id: 3,
    firstAccess: false,
    name: 'Caio Cardoso',
    partOf: true,
    passwordHash: '',
    passwordResetToken: '',
    passwordSalt: '',
    phone: '',
    resetTokenExpires: '',
    role: '',
    rpmId: 3,
    verificationToken: '',
    verifiedAt: ''
  }
]